<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="BasicTests.fs" />
    <None Include="Script.fsx" />
    <Compile Include="LightBulbTest.fs" />
    <Compile Include="BowlingTest.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Contrib\AnyUnit.Constraints\AnyUnit.Constraints.csproj" />
    <ProjectReference Include="..\..\..\..\Contrib\AnyUnit.Style.FsUnit\AnyUnit.Style.FsUnit.fsproj" />
    <ProjectReference Include="..\..\..\..\Contrib\AnyUnit.Style.Xunit\AnyUnit.Style.Xunit.csproj" />
    <ProjectReference Include="..\..\..\..\AnyUnit\AnyUnit.csproj" />
  </ItemGroup>

</Project>
