// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.0.5.0")]
[assembly: AssemblyFileVersionAttribute("1.0.5.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.5.0 (Built Locally)")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.5.0";
    }
}
