// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.8.0.0")]
[assembly: AssemblyFileVersionAttribute("0.8.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.8.0.0 (Built Locally)")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.8.0.0";
    }
}
