//
//  Copyright 2026 AnyUnit Contributors
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.Testing.Platform.Builder;

namespace AnyUnit.TestingPlatform
{
    /// <summary>
    /// A stand-in for the entry point Microsoft.Testing.Platform.MSBuild
    /// would generate, for a test project that cannot host one on
    /// browser-wasm (see the csproj). Awaitable, so the wasm runtime can
    /// yield to the host between MTP's steps.
    /// </summary>
    public static class WasmEntry
    {
        public static async Task<int> Main(string[] args)
        {
            var builder = await TestApplication.CreateBuilderAsync(args);

            // Microsoft.Testing.Platform.MSBuild still generates
            // SelfRegisteredExtensions into the test assembly - the list of
            // every referenced extension's TestingPlatformBuilderHook
            // (its own output device, TRX, AnyUnit's framework
            // registration, ...) - even with the entry point turned off.
            // That is exactly what the generated entry point would have
            // called, so call it. Found by reflection since this assembly
            // knows the test assembly only by name.
            var registered = 0;
            foreach (var assembly in TestAssemblies())
            {
                var hooks = assembly.GetTypes().FirstOrDefault(t => t.Name == "SelfRegisteredExtensions");
                var add = hooks == null ? null : hooks.GetMethod("AddSelfRegisteredExtensions",
                    BindingFlags.Public | BindingFlags.Static, null,
                    new[] { typeof(ITestApplicationBuilder), typeof(string[]) }, null);
                if (add == null)
                    continue;
                add.Invoke(null, new object[] { builder, args });
                registered++;
            }
            if (registered == 0)
                throw new InvalidOperationException(
                    "AnyUnit.TestingPlatform.WasmEntry: no SelfRegisteredExtensions in the test assembly. "
                    + "It should be generated by Microsoft.Testing.Platform.MSBuild when EnableAnyUnitRunner is true.");

            using (var app = await builder.BuildAsync())
            {
                return await app.RunAsync();
            }
        }

        private static IEnumerable<Assembly> TestAssemblies()
        {
            var names = (AppContext.GetData("AnyUnit.TestAssembly") as string ?? "")
                .Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries);
            if (names.Length == 0)
                throw new InvalidOperationException(
                    "AnyUnit.TestingPlatform.WasmEntry: no AnyUnit.TestAssembly runtime host configuration option. "
                    + "The test project should set EnableAnyUnitRunner=true, which emits it.");
            return names.Select(n => Assembly.Load(n.Trim()));
        }
    }
}
