<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Contrib\AnyUnit.Constraints\AnyUnit.Constraints.csproj" />
    <ProjectReference Include="..\..\Contrib\AnyUnit.Style.Nunit\AnyUnit.Style.Nunit.csproj" />
    <ProjectReference Include="..\..\Contrib\AnyUnit.Style.Xunit\AnyUnit.Style.Xunit.csproj" />
    <ProjectReference Include="..\..\AnyUnit\AnyUnit.csproj" />
    <ProjectReference Include="..\Tests\BasicTests\BasicTests.csproj" />
    <ProjectReference Include="..\Tests\ConstraintsTests\ConstraintsTests.csproj" />
    <ProjectReference Include="..\ConventionTestProcessor\ConventionTestProcessor.csproj" />
    <ProjectReference Include="..\Tests\Style\NunitTests\NunitTests.csproj" />
    <ProjectReference Include="..\Tests\Style\XunitTests\XunitTests.csproj" />
    <ProjectReference Include="..\Tests\Style\FsUnitTests\FsUnitTests.fsproj" />
  </ItemGroup>
</Project>
