<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <Description>FsUnit-style F# assertions for AnyUnit.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="FsUnit.fs" />
    <Compile Include="AssertionHelper.fs" />
    <None Include="Script.fsx" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AnyUnit\AnyUnit.csproj" />
    <ProjectReference Include="..\AnyUnit.Constraints\AnyUnit.Constraints.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
